name: Build and Push OCI Image to Registry

on:
  workflow_call:
    inputs:
      rootdir:
        required: true
        type: string
      workdir:
        required: true
        type: string
      image-name:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    continue-on-error: true

    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up QEMU for Docker Buildx
        uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0

      - name: Set up Node.js for extracting recipe from Dockerfile
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          check-latest: true

      - name: Install common dependencies for extracting recipe from Dockerfile
        run: npm i --no-save fs path os

      - name: Set WORKDIR and ROOTDIR
        run: |
          echo "WORKDIR=${{ inputs.workdir }}" >> $GITHUB_ENV
          echo "ROOTDIR=${{ inputs.rootdir }}" >> $GITHUB_ENV

      - name: Extract recipe from Dockerfile
        id: recipe
        run: |
          TAGS=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile tags`
          PLATFORMS=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile platforms`
          VARIANT=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile variant`
          echo TAGS: $TAGS
          echo PLATFORMS: $PLATFORMS
          echo VARIANT: $VARIANT
          {
            echo "tags<<EOF"
            echo "$TAGS"
            echo "EOF"
            echo "platforms<<EOF"
            echo "$PLATFORMS"
            echo "EOF"
            echo "variant=$VARIANT"
          } >> "$GITHUB_OUTPUT"

      - name: Generate Docker image metadata
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        id: meta
        with:
          images: |
            ghcr.io/Stegripe/${{ inputs.image-name }}
          tags: |
            ${{ steps.recipe.outputs.tags }}

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image from the specified Dockerfile
        id: docker_build
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ${{ env.ROOTDIR }}
          file: ${{ env.WORKDIR }}/Dockerfile
          platforms: |
            ${{ steps.recipe.outputs.platforms }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
