name: Build and Push OCI Image to Registry

on:
  workflow_call:
    inputs:
      rootdir:
        required: true
        type: string
      workdir:
        required: true
        type: string
      image-name:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    continue-on-error: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up QEMU for Docker Buildx
        uses: docker/setup-qemu-action@49b3bc8e6bdd4a60e6116a5414239cba5943d3cf # v3.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Set up Node.js for extracting recipe from Dockerfile
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: 20
          check-latest: true

      - name: Install common dependencies for extracting recipe from Dockerfile
        run: npm i --no-save fs path os

      - name: Set WORKDIR and ROOTDIR
        run: |
          echo "WORKDIR=${{ inputs.workdir }}" >> $GITHUB_ENV
          echo "ROOTDIR=${{ inputs.rootdir }}" >> $GITHUB_ENV

      - name: Extract recipe from Dockerfile
        id: recipe
        run: |
          TAGS=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile tags`
          PLATFORMS=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile platforms`
          VARIANT=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile variant`
          echo TAGS: $TAGS
          echo PLATFORMS: $PLATFORMS
          echo VARIANT: $VARIANT
          echo "::set-output name=tags::${TAGS//$', '/'%0A'}"
          echo "::set-output name=platforms::${PLATFORMS//$', '/'%0A'}"
          echo "::set-output name=variant::$VARIANT"

      - name: Generate Docker image metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: meta
        with:
          images: |
            ghcr.io/Stegripe/${{ inputs.image-name }}
          tags: |
            ${{ steps.recipe.outputs.tags }}

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image from the specified Dockerfile
        id: docker_build
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: ${{ env.ROOTDIR }}
          file: ${{ env.WORKDIR }}/Dockerfile
          platforms: |
            ${{ steps.recipe.outputs.platforms }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
