name: Build and Push Python UV to OCI Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "python/uv/Dockerfile"
      - "python/entrypoint.sh"
  pull_request:
    branches:
      - "**"
    paths:
      - "python/uv/Dockerfile"
      - "python/entrypoint.sh"
  workflow_dispatch:

jobs:

  python-uv:
    name: Python UV

    uses: ./.github/workflows/build.yml
    with:
      rootdir: python
      workdir: python/uv
      image-name: python
    secrets: inherit
